### ISSUE TITLE
Creating custom resource object from yaml

### ISSUE THREAD

**Issue by srajeev** [hagay3/skuber#165]
Hello -

How can we create objects from yaml?
I mean I can create an Argo EventBus Custom resource using  kubectl apply -f test-eventbus.yaml
How can I create the same programmatically  using skuber API?

---- test-eventbus.yaml -----
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: test1-event-bus
spec:
  nats:
    native: {}

Thank you!

**Comment by hagay3** [comment]
Thank you for creating this issue.
skuber is a typed library, meaning every object needs to be defined as a case class .
You can extend `CustomResource` and define EventBus
Here is an example of how to do it
https://github.com/hagay3/skuber/blob/master/client/src/it/scala/skuber/CustomResourceSpec.scala
Then, for creating EventBus instance you need to call skuber create API:
https://github.com/hagay3/skuber/blob/master/client/src/it/scala/skuber/CustomResourceSpec.scala#L120

@srajeev  Let me know if this answer satisfies your question.

**Comment by srajeev** [comment]
Thank you!  

I am not trying to create a  new CustomerResourceDefinition.
When I installed argo-events project, it comes with EventBus CustomResourceDefinition. So, it already exists.  I am just trying to create an EventBus object with name  'default'  (as in my yaml I posted earlier), in a given namespace.  Is this possible Skuber?  Just like what I get with `kubectl apply -f test-eventbus.yaml`

EventBus resource is under the Package -> name - v1alpha1 is the v1alpha1 version of the API.
https://github.com/argoproj-labs/argo-eventbus/blob/main/api/event-bus.md

---- test-eventbus.yaml -----
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
name: default
namespace: test1-event-bus
spec:
nats:
native: {}

**Comment by hagay3** [comment]
@srajeev 
Hi,
The following code should give you what you wish. 
Let me know if its solved the problem.
skuber needs the case class EventBus in order to be able to send k8s API the parsed json.


https://github.com/hagay3/skuber/blob/master/examples/src/main/scala/skuber/examples/argo/EventBusExample.scala
