### ISSUE TITLE
Scala 3?

### ISSUE THREAD

**Issue by PhilAndrew** [hagay3/skuber#199]
Can support Scala 3?

**Comment by hagay3** [comment]
Hi @PhilAndrew 
Thank you for opening the issue and showing interest in skuber.

I have started working on scala 3 support here #200 
In case you want to put some effort, you can fork the branch and see the deprecations errors.
https://github.com/hagay3/skuber/runs/7591046095?check_suite_focus=true

**Comment by hagay3** [comment]
@PhilAndrew 
scala 3.0 released
