### ISSUE TITLE
Support for Bound Service Account Token Volume for In-Cluster communication (kubernetes 1.22)

### ISSUE THREAD

**Issue by jahzielHA** [hagay3/skuber#204]
**Is your feature request related to a problem? Please describe.**
When **in-cluster configuration** running in kubernetes 1.22 the service account token mounted on the pod (filesystem) expires and gets refreshed periodically by the kubelet. Skuber does not take into account this, it caches the token and will use it once expired.

**Describe the solution you'd like**
Skuber needs to periodically reload the token from the filesystem.

**Describe alternatives you've considered**
This is a change in the behaviour on how service account tokens work in kubernetes after the version 1.21. This feature is required or skuber won't work for in-cluster communication on kubernetes 1.22.

**Additional context**
Resources about the Bound Service Account Token Volume feature
[GCloud - kubernetes-bound-service-account-tokens](https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-bound-service-account-tokens)
[service-accounts-admin/#bound-service-account-token-volume](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#bound-service-account-token-volume)

**Comment by hagay3** [comment]
Hi @jahzielHA 
Thank you for opening the issue and showing interest in skuber.

This feature is already implemented in skuber, you will need to provide skuber `.kube/config` file, and also the pod that skuber running on needs `gcloud` cli on it.
An example for the kube config can be found here
https://github.com/hagay3/skuber/blob/master/client/src/test/scala/skuber/api/ConfigurationSpec.scala

Since I don't have access to a GCP cluster, I can't test it by myself, I will try my best to help you here.
in case you want we can also talk over skuber discord channel 
https://discord.gg/byEh56vFJR

**Comment by jahzielHA** [comment]
Hi @hagay3 
Thanks for your quick response.

Apologies if I am mistaken, this issue happens for in-cluster, where the token is picked up from the filesystem (**_/var/run/secrets/kubernetes.io/serviceaccount/token_**) inside the POD. This is how the PODs can communicate with the Kubernetes API and how Skuber configures the client for in-cluster communication. No KUBECONFIG involved since it all happens inside the same Kubernetes cluster.
See: https://github.com/hagay3/skuber/blob/master/client/src/main/scala/skuber/api/Configuration.scala#L243-L246

On Kubernetes 1.22 this token (filesystem => /var/run/secrets/kubernetes.io/serviceaccount/token) will be "refreshed" by the kubelet since it will be mounted by the Bound Service Account Token Volume. Before Kubernetes 1.22 it was a static token and could be used during the whole lifetime of the POD.

Happy to discuss this over discord if needs be.

Thanks for the help!

**Comment by hagay3** [comment]
I totally understand that right now you are not using kubeconfig.
Skuber will be able to catch the new token from the service account with `gcloud` cli.
But for this feature you want to achieve, there are 2 prerequisites:
1. Skuber need to work with kubeconfig file (you can place it on the pod or have it applicative).
2. Install gcloud cli on the pod
Let's continue on discord I'm available there
https://discord.gg/byEh56vFJR

**Comment by hagay3** [comment]
After a discussion with @jahzielHA ,
The suggestion is to add a "refresh" token mechanism to in-cluster configuration.
1. Create new class `FileTokenAuthRefreshable extends AuthProviderRefreshableAuth`
2. The class will get the token path to refresh and every 5 minutes will fetch the new token from the path provided.
3. An example can be taken from `GcpAuth` and `AwsAuthRefreshable`
4. Replace `TokenAuth` with `FileTokenAuthRefreshable` in the in-cluster configuration code
https://github.com/hagay3/skuber/blob/master/client/src/main/scala/skuber/api/Configuration.scala#L271
5. Add documentation about using in-cluster configurations + note its refreshes the token automatically.
https://skuber.co/#/?id=configuration
