### ISSUE TITLE
Add ability to delete objects in namespace

### ISSUE THREAD

**Issue by antontroshin** [hagay3/skuber#44]
Current methods "delete" and "deleteWithOptions" will take "default" namespace from the context.
Either add new param to these methods or new signature , i.e. "deleteInNamespace" and "deleteInNamespaceWithOptions".

**Comment by chessman** [comment]
@antontroshin it's here https://github.com/hagay3/skuber/blob/master/client/src/main/scala/skuber/api/client/KubernetesClient.scala#L361-L367

**Comment by antontroshin** [comment]
@chessman nice one. Worked like a charm. 
Thanks a lot!
